ProFour/ProFour/urls.py
from django.contrib import admin
from django.urls import path,include
from appfour import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('appfour/',include('appfour.urls')),
    path("logout/",views.user_logout,name="logout"),
    # path("my_profile/",views.my_profile,name="my_profile"),
]

ProFour/appfour/urls.py
from django.urls import path,include
from appfour import views


app_name= 'appfour'

urlpatterns = [
    path('registration/',views.register, name='registration'),
    path('login/',views.user_login, name='login'),
    path('my_profile/',views.my_profile, name='my_profile'),
]

ProFour/appfour/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):

    my_user=models.OneToOneField(User,on_delete=models.CASCADE)

    protfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.my_user.username

ProFour/appfour/forms.py
from django import forms
from django.contrib.auth.models import User
from appfour.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('protfolio_site','profile_pic')

ProFour/appfour/views.py
from django.shortcuts import render
from appfour.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.




def index(request):
    context_dic={'text':"Please go to login"}
    return render(request,'appfour/index.html', context=context_dic)

def register(request):

    registered=False

    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.my_user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'appfour/registration.html',
                        {'user_form':user_form,
                          'profile_form':profile_form,
                          'registered':registered})

def user_login(request):
    print("im in")
    if request.method =="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return render(request,'appfour/my_profile.html')
            else:
                return HttpResponse("account not active")
        else:
            print("faild log in accure")
            print("user name: {} and password {}".format(username,password))
            return HttpResponse ("user name or password are not maching")
    else:
        print("im in else")
        return render(request,'appfour/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def my_profile(request):
    return render(request,'appfour/my_profile.html')

ProFour/templates/appfour/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <ul class="nav navbar-nav">

          <li> <a class="navbar-brand" href="{% url 'index' %}">Index</a></li>
          <li> <a class="nav-link" href="{% url 'admin:index' %}">admin</a></li>
          <li> <a class="nav-link" href="{% url 'appfour:registration' %}">Registration</a></li>
          <li> <a class="nav-link" href="{% url 'appfour:my_profile' %}">my profile</a></li>
          {% if user.is_authenticated %}
            <li> <a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li> <a class="nav-link" href="{% url 'appfour:login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>

    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock%}

    </div>
  </body>
</html>

ProFour/templates/appfour/index.html
{% extends "appfour/basic.html"%}
{%block body_block%}

<div class="jumbotron">
  <h1>welcome to Index</h1>
</div>

    <h1>{{text|lower}}</h1>

{%endblock%}

ProFour/templates/appfour/login.html
{% extends "appfour/basic.html"%}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login</h1>
  <form action="{% url 'appfour:login' %}" method="post">
    {% csrf_token %}
    <label for="username">User Name:</label>
    <input type="text" name="username" placeholder="enter user name">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="login">
  </form>
</div>



{% endblock %}

ProFour/templates/appfour/my_profile.html
{% extends "appfour/basic.html"%}
{%block body_block%}

<div class="jumbotron">
  <h1>welcome to your profile</h1>
</div>
{%endblock%}

ProFour/templates/appfour/registration.html
{% extends "appfour/basic.html"%}
{% load staticfiles%}

{%block body_block%}


<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering!</h1>

  {% else %}

  <h1>register here</h1>
  <form  enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}

    <input type="submit" name="" value="Register">

  </form>


  {%endif%}
</div>


{%endblock%}